![title](1.png)

In [1]:
import numpy as np

In [7]:
a = np.array([[0,   0, 0, 1/3, 0,   0],
              [1/4, 0, 0, 0,   1/2, 0],
              [0,   1, 0, 1/3, 1/2, 0],
              [1/4, 0, 0, 0,   0,   1],
              [1/4, 0, 1, 1/3, 0,   0],
              [1/4, 0, 0, 0,   0,   0]])

In [8]:
b = np.array([1/6,1/6,1/6,1/6,1/6,1/6])
w = b

In [6]:
# 简化模型
def work(a,w):
    for i in range(100):
        w = np.dot(a,w)
        print(w)
    return w

In [9]:
# 随机模型
def random_work(a,w,n):
    d = 0.85
    for i in range(100):
        w = (1-d)/n + d * np.dot(a,w)
        print(w)
    return w

In [10]:
work(a,w)

[0.05555556 0.125      0.30555556 0.20833333 0.26388889 0.04166667]
[0.06944444 0.14583333 0.32638889 0.05555556 0.38888889 0.01388889]
[0.01851852 0.21180556 0.3587963  0.03125    0.36226852 0.01736111]
[0.01041667 0.18576389 0.40335648 0.02199074 0.37384259 0.00462963]
[0.00733025 0.18952546 0.38001543 0.0072338  0.4132909  0.00260417]
[0.00241127 0.20847801 0.39858218 0.00443673 0.38425926 0.00183256]
[0.00147891 0.19273245 0.40208655 0.00243538 0.4006639  0.00060282]
[8.11792695e-04 2.00701678e-01 3.93876190e-01 9.72543724e-04
 4.03268068e-01 3.69727366e-04]
[3.24181241e-04 2.01836982e-01 4.02659894e-01 5.72675540e-04
 3.94403319e-01 2.02948174e-04]
[1.90891847e-04 1.97282705e-01 3.99229534e-01 2.83993484e-04
 4.02931831e-01 8.10453104e-05]
[9.46644947e-05 2.01513638e-01 3.98843285e-01 1.28768272e-04
 3.99371921e-01 4.77229617e-05]
[4.29227573e-05 1.99709627e-01 4.01242522e-01 7.13890854e-05
 3.98909874e-01 2.36661237e-05]
[2.37963618e-05 1.99465667e-01 3.99188360e-01 3.43968130e-0

array([1.47911420e-31, 2.00000000e-01, 4.00000000e-01, 2.21867130e-31,
       4.00000000e-01, 7.39557098e-32])

In [12]:
random_work(a,w,6)

[0.07222222 0.13125    0.28472222 0.20208333 0.24930556 0.06041667]
[0.08225694 0.14630208 0.29977431 0.09170139 0.33961806 0.04034722]
[0.05098206 0.18681727 0.3196765  0.07677474 0.32326982 0.0424796 ]
[0.04675284 0.17322336 0.3429372  0.07194135 0.32931156 0.03583369]
[0.04538338 0.17489239 0.33258065 0.06539361 0.34681498 0.03493498]
[0.04352819 0.18204034 0.33958309 0.0643387  0.33586571 0.03464397]
[0.0432293  0.17699267 0.34070651 0.06369711 0.34112467 0.03424974]
[0.04304752 0.17916421 0.33846927 0.06329851 0.34183428 0.03418623]
[0.04293458 0.17942716 0.34050372 0.06320589 0.33978105 0.0341476 ]
[0.04290834 0.17853054 0.33982837 0.06314906 0.3414601  0.0341236 ]
[0.04289223 0.17923856 0.33976374 0.06312308 0.34086437 0.03411802]
[0.04288487 0.17898196 0.34010501 0.06311492 0.34079865 0.0341146 ]
[0.04288256 0.17895246 0.33985665 0.06311044 0.34108485 0.03411304]
[0.04288129 0.17907361 0.33995195 0.06310862 0.34087199 0.03411254]
[0.04288078 0.17898287 0.33996394 0.06310794 0.3

array([0.04288042, 0.17901327, 0.33994289, 0.06310737, 0.34094396,
       0.03411209])